### ISSUE TITLE
Feature: Browser only actor

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica-feature-solid#17]
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

I'm running into some issues when trying to bundle up this package using Webpack as the following packages do not have polyfills despite being required somewhere in the dependency tree
```ts
fs: false,
http2: false,
tls: false,
net: false,
child_process: false,
dns: false
```

On the other hand packaging up `@comunica/actor-init-sparql` - has no problems.

I suspect the cause is the authentication package is node so it would be good to have an init actor (e.g. `@comunica/actor-init-solid-sparql-browser`) that does not use this.

**Comment by jeswr** [comment]
Discovered I can bundle it up fine if I use webpack v4 - happy to create a PR that adds the webpack files if you want.

**Comment by rubensworks** [comment]
Oh, apparently I wasn't subscribed yet to this repo, so I missed the issue.

We can probably just do the same as in packages like `@comunica/actor-init-sparql-file`: https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql-file/webpack.config.js

> I suspect the cause is the authentication package is node so it would be good to have an init actor (e.g. @comunica/actor-init-solid-sparql-browser) that does not use this.

Yeah, I made an isomorphic version of the auth package that works fine in both Node and browser.

**Comment by jeswr** [comment]
> We can probably just do the same as in packages like @comunica/actor-init-sparql-file: https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql-file/webpack.config.js

Since the webpack.config.js is not included in the [@comunica/actor-init-sparql npm distribution](https://unpkg.com/browse/@comunica/actor-init-sparql@1.22.3/) - one can't extend from it in packages outside of the monrepo that it is in.

The config that I had working just copy/pasted contents from @comunica/actor-init-sparql instead - not sure if there is a cleaner way of doing this

**Comment by rubensworks** [comment]
Ah, right. Yeah, copy-pasting is fine then. Perhaps just add a comment at the top of the file to say from where it has been copied, and what parts have been modified (in case we have to change things in the future).
