### ISSUE TITLE
Possibly missing sparqlee dependency

### ISSUE THREAD

**Issue by jeswr** [comunica/comunica-feature-solid#25]
#### Issue type:

- :bug: Bug 

____
#### Description:

____
#### Environment:

I was trying to upgrade ldflex-comunica and encountered these failing workflows https://github.com/LDflex/LDflex-Comunica/runs/5418367001?check_suite_focus=true#step:4:12 - it would seem to indicate that sparqlee is missing as a dependency?

**Comment by rubensworks** [comment]
The file is there though, but it's in lowercase. Weird that we're only seeing this issue now, as it has been like this for a while AFAIK. The new release of sparqlee (2.0.2) fixes this.
